# Generated by Django 5.0.1 on 2024-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_alter_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number_of_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
